title: Space Finder - University of Leeds
email: p.l.edwards@leeds.ac.uk
description: >-
  Map-driven application originally developed by
  the University of Cambridge
  https://spacefinder.lib.cam.ac.uk/
baseurl: ""
url: "https://https://spacefinder.leeds.ac.uk/"
host: "localhost"
google_analytics: "G-6LHKST5028"
photo_dir: "/assets/photos/"
sass:
  style: compressed
plugins:
  - jekyll-feed

