title: Space Finder - University of Leeds
email: p.l.edwards@leeds.ac.uk
description: >-
  Spacefinder is an application designed for students
  to locate study spaces at the University of Leeds. It
  includes detailed descriptions of each space, filters
  based on space characteristics, and  navigation via a
  map.
environment: development
baseurl: ""
url: "https://dev.spacefinder.leeds.ac.uk"
host: "localhost"
photo_dir: "/assets/photos/"
lang: "en"
dc:
  creator: "University of Leeds"
  dateCreated: "2022-06-06"
  dateModified: "2022-10-13"
  publisher: "University of Leeds"
  spatialCoverage: "University of Leeds campus"
  types:
    - "InteractiveResource"
  subjects:
    - "Digital mapping"
    - "College Campuses"
sass:
  style: compressed
plugins:
  - jekyll-feed

