title: Spacefinder
email: p.l.edwards@leeds.ac.uk
description: >-
  Map-driven application originally developed by
  the University of Cambridge
  https://spacefinder.lib.cam.ac.uk/
baseurl: "/spacefinder-ui"
url: "https://uol-library.github.io"
host: "localhost"
photo_dir: "/spacefinder-ui/assets/photos/"
google_maps_api_key: "AIzaSyBrAkYSJYjm6k9ultU71meFVsvxWR--97o"
google_analytics: ""
sass:
  style: compressed
plugins:
  - jekyll-feed

