name: concat-spacefinder-data
on: workflow_dispatch
jobs:
  concat-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Concat spaces files
        run: npm run concat
      - name: Commit changes
        run: | 
          git config --global user.name 'peteredwards'
          git config --global user.email 'p.l.edwards@leeds.ac.uk'
          git commit -am "Master space data file generation"
          git push

