name: concat-spacefinder-data
on: [push]
jobs:
  concat-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm run concat
